### ISSUE TITLE
请说明下该项目适配的node和npm版本

### ISSUE THREAD

**Issue by baymax55** [Jarrettluo/all-documents-vue#12]
我在 v16.20.1 版本下执行 `npm i `命令报错

npm WARN deprecated core-js@2.3.0: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature dete
ction in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path D:\code\github\all-documents-vue\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\devPrograms\node-v16.20.1-win-x64\node.exe D:\code\github\all-documents-vue\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'D:\\devPrograms\\node-v16.20.1-win-x64\\node.exe',
npm ERR! gyp verb cli   'D:\\code\\github\\all-documents-vue\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.20.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\code\github\all-documents-vue\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\code\github\all-documents-vue\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\code\github\all-documents-vue\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\code\github\all-documents-vue\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\code\github\all-documents-vue\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\code\github\all-documents-vue\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\code\github\all-documents-vue\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\code\github\all-documents-vue\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\code\github\all-documents-vue\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\code\github\all-documents-vue\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\code\github\all-documents-vue\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\code\github\all-documents-vue\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:402:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! gyp ERR! System Windows_NT 10.0.23570
npm ERR! gyp ERR! command "D:\\devPrograms\\node-v16.20.1-win-x64\\node.exe" "D:\\code\\github\\all-documents-vue\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\code\github\all-documents-vue\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.20.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Local\npm-cache\_logs\2023-10-25T01_32_28_949Z-debug-0.log

**Comment by baymax55** [comment]
使用 node14.15版本即可解决
https://stackoverflow.com/questions/71599040/i-cannot-run-any-project-because-of-gyp-error-how-can-i-fix-this-npm-err-gyp
